# https://github.com/roboll/helmfile

# we can use Helm 3 if its present in the container image
helmBinary: helm3

helmDefaults:
  wait: true
  timeout: 180 # seconds

# extra Helm repositories
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: something-else
    url: http://charts.example.com

# all the releases we want to install in a preview env
releases:

  - # the main application's chart
    name: {{ .Values.preview.releaseName }}
    namespace: {{ .Values.preview.namespace }}
    chart: ../{{ requiredEnv "APP_NAME" }}
    values:
      - values.yaml.gotmpl

  - # we can include other releases as well
    name: postgresql
    namespace: 
    chart: bitnami/postgresql
    version: 8.9.2
    values:
      - postgresql.yaml
